name: Linting

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Lint
        run: |
          npm run dev &
          npm run lint:svelte
          npm run lint:prettier
          npm run lint:eslint
          npm run lint:a11y
      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --build --prod --message "${{ github.event.commits[0].message }}"
