name: Linting

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Lint
        run: |
          npm run dev &
          npm run lint:svelte
          npm run lint:prettier
          npm run lint:eslint
